language: php
php:
  - "7.3"
  - "7.4"

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - travis_retry composer install

script:
  - composer test
  - composer analyse
  - composer codestyle

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
